name: "golang deadcode action"
description: "Run the golang deadcode checker"
author: "opzkit"
inputs:
  packages:
    description: 'Run deadcode on these packages.'
    required: false
    default: './...'
  go-version-file:
    description: 'Path to the go.mod file.'
    required: false
  go-version:
    description: 'The go version to use when running deadcode check'
    required: false
  check-latest:
    description: 'Set this option to true if you want the action to always check for the latest available version that satisfies the version spec'
    default: false
  godeadcode-version:
    description: 'The deadcode version to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        check-latest: ${{ inputs.check-latest }}
    - name: Get deadcode
      run: go install golang.org/x/tools/cmd/deadcode@${{ inputs.godeadcode-version }}
      shell: bash
    - name: Run go deadcode
      run: deadcode --test ${{ inputs.packages }}
      shell: bash

branding:
  icon: 'alert-triangle'
  color: 'red'
